// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { env } from "@/config/env";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with retry and error handling
const supabaseUrl = (env.VITE_SUPABASE_URL || "https://placeholder.supabase.co").trim();
const supabaseKey = (env.VITE_SUPABASE_PUBLISHABLE_KEY || "placeholder-key").trim();

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      "x-client-info": "dobeu-web@1.0.0",
    },
  },
});

/**
 * Health check for Supabase connection
 */
export async function checkSupabaseHealth(): Promise<boolean> {
  try {
    const { error } = await supabase.from("profiles").select("count").limit(1);
    return !error;
  } catch {
    return false;
  }
}
